integration-1-to-master
RomanL88/taxi24 pull request #1
Opened 2022-02-20 08:30 UTC by RomanL88

2022-02-22 06:12 UTC, NizamovArturV requested changes

2022-02-22 06:12 UTC, NizamovArturV commented on .main.menu.php
> +		"/about/index.php",
index.php в ссылке не нужен, если переходить по слешу он автоматически подключает index.php

2022-02-22 06:12 UTC, NizamovArturV commented on local/php_interface/sprint.options.php
> +    ->addTab('О компании')
Не разделять опции на отдельные табы - объединить их по смыслу

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/components/bitrix/menu/menu/template.php
> +</div>
Если открытие div находится за условием, то и закрытие должно быть за условием

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/components/bitrix/menu/menu/template.php
> +<? if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die(); ?>
Отформатировать файл по отступам

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/components/bitrix/menu/menuForMobile/template.php
> +</div>
Если открытие div находится за условием, то и закрытие должно быть за условием

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/components/bitrix/menu/menuForMobile/template.php
> +<? if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die(); ?>
Отформатировать файл по отступам

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/footer.php
> +/* if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
Строчку расскоментировать, почитать для чего она нужна и ответить мне здесь в комментариях

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/footer.php
> +					<!-- 					<a href="tel:+79991234569" class="gray bt">+7 (999) 123-45-69</a><br>
Зачем эту строчку оставлять закомментированной?

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/footer.php
> +<?
Файл должен содержать только верстку, в рамках первого заданиях необходимо выполнить только интеграцию шапки, футер должен быть во втором задании

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/footer.php
> +$APPLICATION->AddHeadScript(SITE_TEMPLATE_PATH . '/https://unpkg.com/swiper@7/swiper-bundle.min.js');
Скрипты подключать через функцию Asset::getInstance()->addJs и подключать их в файле header.php

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/header.php
> +<html>
Лишний комментарий

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/header.php
> +	<?php /*$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH . './css/aos.css'); */ ?>
Лишняя строка

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/header.php
> +	<div class="sub_header">
Убрать из шапки слайдер - он должен быть только на главной странице

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/header.php
> +					"MENU_CACHE_TYPE" => "N",	// Тип кеширования
Меню не кэшируется, поставить автокэширование

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/header.php
> +					"MENU_CACHE_TYPE" => "N",	// Тип кеширования
Меню не кэшируется, поставить автокэширование

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/header.php
> +					"USE_EXT" => "Y",	// Подключать файлы с именами вида .тип_меню.menu_ext.php
Этот параметр зачем включен? Ответить в комментариях

2022-02-22 06:12 UTC, NizamovArturV commented on local/templates/main/header.php
> +					"USE_EXT" => "Y",	// Подключать файлы с именами вида .тип_меню.menu_ext.php
Этот параметр зачем включен? Ответить в комментариях

2022-02-22 07:34 UTC, RomanL88 commented on local/templates/main/header.php
> +					"USE_EXT" => "Y",	// Подключать файлы с именами вида .тип_меню.menu_ext.php
насколько правильно понял, он позволяет делать меню динамическим.
Не будет видно пунктов меню в админке, так как он перебором подключает пункты меню из файла (массива
)

2022-02-22 13:09 UTC, NizamovArturV commented on local/templates/main/header.php
> +					"USE_EXT" => "Y",	// Подключать файлы с именами вида .тип_меню.menu_ext.php
Не верно, посмотри еще

2022-02-24 07:08 UTC, RomanL88 commented on local/templates/main/header.php
> +					"USE_EXT" => "Y",	// Подключать файлы с именами вида .тип_меню.menu_ext.php
Подключать файлы с именами вида .тип_меню.menu_ext.php
Это сделано для динамического меню, верно?

2022-02-28 06:08 UTC, NizamovArturV requested changes

2022-02-28 06:08 UTC, NizamovArturV commented on local/templates/main/header.php
> +<html>
Не выполнено

2022-02-28 06:08 UTC, NizamovArturV commented on local/templates/main/header.php
> +	<?php /*$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH . './css/aos.css'); */ ?>
Не выполнено

2022-02-28 06:08 UTC, NizamovArturV commented on local/templates/main/header.php
> +	<script src="<? CUtil::GetAdditionalFileURL('https://unpkg.com/swiper@7/swiper-bundle.min.js') ?>"></script>
Скрипты подключать функцией Asset::getInstance()->addJs

2022-02-28 06:08 UTC, NizamovArturV commented on local/templates/main/header.php
> +					"USE_EXT" => "Y",	// Подключать файлы с именами вида .тип_меню.menu_ext.php
Верно, чтобы не просто описывать массив напрямую, а например сделать меню из разделов инфоблока, которые ты контролировать не можешь. Таких файлов у тебя нет, соотвественно, опицию нужно отключить для отключения лишних запросов

2022-02-28 06:08 UTC, NizamovArturV commented on local/templates/main/footer.php
> +<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>
Скрипты подключать функцией Asset::getInstance()->addJs в шапке

2022-02-28 12:07 UTC, NizamovArturV requested changes

2022-02-28 12:07 UTC, NizamovArturV commented on local/templates/main/header.php
> +Asset::getInstance()->addJs(AOS . init());
С такой конструкцией у тебя нет ошибок в консоли браузера? Все скрипты подключаются?

2022-02-28 12:07 UTC, NizamovArturV commented on local/templates/main/header.php
> +	<script src="<? CUtil::GetAdditionalFileURL('https://unpkg.com/swiper@7/swiper-bundle.min.js') ?>"></script>
Не выполнено

2022-02-28 12:07 UTC, NizamovArturV commented on local/templates/main/header.php
> +					"USE_EXT" => "Y",	// Подключать файлы с именами вида .тип_меню.menu_ext.php
Не выполнено

2022-02-28 12:07 UTC, NizamovArturV commented on local/templates/main/header.php
> +					"USE_EXT" => "Y",	// Подключать файлы с именами вида .тип_меню.menu_ext.php
Не выполнено

2022-03-02 10:43 UTC, NizamovArturV approved these changes

2022-03-02 11:11 UTC, merged