Task/5 section about us new
RomanL88/taxi24 pull request #7
Opened 2022-03-01 11:57 UTC by RomanL88

2022-03-16 06:24 UTC, NizamovArturV requested changes

2022-03-16 06:24 UTC, NizamovArturV commented on about/index.php
> +	"news",
Название шаблона должно отражать суть, это у тебя не новости

2022-03-16 06:24 UTC, NizamovArturV commented on about/index.php
> +			1 => "detail_title",
Не используемые свойства нужно убрать

2022-03-16 06:24 UTC, NizamovArturV commented on index.php
> +</section> <br>
Почему два раза секция закрывается? Это в верстке так?

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/menu/menuForMobile/template.php
> +</div>
Вернулись старые изменения, нужно исправить

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news.list/about_block/template.php
> +		/* echo '<pre>';
Не убран комментарий

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/news/bitrix/news.detail/.default/template.php
> +var_dump($arParams["USE_SHARE"]);
Дебажная фукнция осталась

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/news/bitrix/news.detail/.default/template.php
> +<a href="<?= 'https://taxi24.local' . CFile::GetPath($arResult["PROPERTIES"]["ATT_FILE"]["VALUE"]); ?>" download>скачать файл</a>
Ссылка должна быть не абсолютной, а относительной, фразу "Скачать файл" в языковой файл, добавить проверку на непустое значение перед выводом

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/news/bitrix/news.detail/.default/template.php
> +	<? if ($arResult["NAV_RESULT"]) : ?>
Убрать лишний код, в задании четко написано, что именно нужно вывести на детальной странице

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/news/bitrix/news.list/.default/template.php
> +	/* 	echo '<pre>';
Остался комментарий

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/news/bitrix/news.list/.default/template.php
> +<? if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();
Почистить код, много не нужных выводов

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/news/bitrix/news.list/list/template.php
> +<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
Удалить неиспользуемый шаблон

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/news/bitrix/news.list/photo/template.php
> +<? if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die(); ?>
Удалить неиспользуемый шаблон

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/news/detail.php
> +<p><a href="<?= $arResult["FOLDER"] . $arResult["URL_TEMPLATES"]["news"] ?>"><?= 'Назад' ?></a></p>
Назад в языковой файл. И зачем выводить его через php теги, если бы можно было просто написать Назад в html?) Это замечание на будущее

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/news/detail.php
> +<? $ElementID = $APPLICATION->IncludeComponent(
Зачем значение шаблона записывать в переменную?

2022-03-16 06:24 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/news/news.php
> +<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
Убрать лишние подключения компонентов

2022-03-16 06:24 UTC, NizamovArturV commented on about/style.css
> +footer {
Что за файл? Он нигде не подключается

2022-03-16 06:31 UTC, RomanL88 commented on about/index.php
> +	"news",
сменил название на slider-benefits

2022-03-16 09:56 UTC, RomanL88 commented on local/templates/main/components/bitrix/news/news/detail.php
> +<p><a href="<?= $arResult["FOLDER"] . $arResult["URL_TEMPLATES"]["news"] ?>"><?= 'Назад' ?></a></p>
типо программист же)

2022-03-18 06:48 UTC, NizamovArturV requested changes

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/bitrix/news.detail/.default/template.php
> +<? if ($arResult["PROPERTIES"]["ATT_FILE"]["VALUE"] != "") : ?>
Достаточно просто сделать if $arResult["PROPERTIES"]["ATT_FILE"]["VALUE"], потому что там может содержатся не пустая строка, а например 0

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/bitrix/news.detail/.default/template.php
> +	<a href="<?= CFile::GetPath($arResult["PROPERTIES"]["ATT_FILE"]["VALUE"]); ?>" download><?= GetMessage("DOWNLOAD_FILE") ?></a>
Для языковых переменных использовать класс Loc

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/bitrix/news.detail/.default/template.php
> +	<a href="<?= CFile::GetPath($arResult["PROPERTIES"]["ATT_FILE"]["VALUE"]); ?>" download><?= GetMessage("DOWNLOAD_FILE") ?></a>
Для языковых переменных использовать класс Loc

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/bitrix/news.list/.default/template.php
> +<div class="news-list">
Где проверка на подключение пролога?

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/bitrix/news.list/.default/template.php
> +<div class="news-list">
Где проверка на подключение пролога?

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/detail.php
> +<p><a href="<?= $arResult["FOLDER"] . $arResult["URL_TEMPLATES"]["news"] ?>"><?= GetMessage('BACK'); ?></a></p>
Использовать методы нового ядра для языковых переменных

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/detail.php
> +<p><a href="<?= $arResult["FOLDER"] . $arResult["URL_TEMPLATES"]["news"] ?>"><?= GetMessage('BACK'); ?></a></p>
Использовать методы нового ядра для языковых переменных

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/news.php
> +<? if ($arParams["USE_RSS"] == "Y") : ?>
Где подключение пролога? И зачем тебе rss?

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/news.php
> +<? if ($arParams["USE_RSS"] == "Y") : ?>
Где подключение пролога? И зачем тебе rss?

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/news.php
> +<? if ($arParams["USE_SEARCH"] == "Y") : ?>
Поиска у тебя тоже нет

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/news.php
> +<? if ($arParams["USE_SEARCH"] == "Y") : ?>
Поиска у тебя тоже нет

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/news.php
> +<? if ($arParams["USE_FILTER"] == "Y") : ?>
Фильтра тоже

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/news.php
> +<? if ($arParams["USE_FILTER"] == "Y") : ?>
Фильтра тоже

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/system.pagenavigation/pagenavigation_in_about/template.php
> +                        |&nbsp;<a href="<?= $arResult["sUrlPath"] ?>?<?= $strNavQueryString ?>SHOWALL_<?= $arResult["NavNum"] ?>=0" rel="nofollow"><?= GetMessage("nav_paged") ?></a>&nbsp;
Методы нового ядра для языковых переменных

2022-03-18 06:48 UTC, NizamovArturV commented on local/templates/main/components/bitrix/system.pagenavigation/pagenavigation_in_about/template.php
> +                        |&nbsp;<a href="<?= $arResult["sUrlPath"] ?>?<?= $strNavQueryString ?>SHOWALL_<?= $arResult["NavNum"] ?>=0" rel="nofollow"><?= GetMessage("nav_paged") ?></a>&nbsp;
Методы нового ядра для языковых переменных

2022-03-18 09:39 UTC, RomanL88 commented on local/templates/main/components/bitrix/news/slider-benefits/bitrix/news.detail/.default/template.php
> +	<a href="<?= CFile::GetPath($arResult["PROPERTIES"]["ATT_FILE"]["VALUE"]); ?>" download><?= GetMessage("DOWNLOAD_FILE") ?></a>
Спасибо, что напомнил

2022-03-21 10:54 UTC, NizamovArturV approved these changes

2022-03-21 10:54 UTC, NizamovArturV commented on local/templates/main/components/bitrix/news/slider-benefits/bitrix/news.detail/.default/template.php
> +<? if ($arResult["PROPERTIES"]["ATT_FILE"]["VALUE"] != "") : ?>
Достаточно просто сделать if $arResult["PROPERTIES"]["ATT_FILE"]["VALUE"], потому что там может содержатся не пустая строка, а например 0

2022-03-21 11:11 UTC, merged